---

- name: Create instance(s)
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    service_account_email: 2287590306-m6mip51l0ju92bf2kignpoeehbfca108@developer.gserviceaccount.com
    pem_file: /Users/lane/google/pkey.pem
    project_id: linear-arcadia-847
    machine_type: n1-standard-1
    image: debian-7

  tasks:

   - name: Launch instances
     gce:
         instance_names: dev
         machine_type: "{{ machine_type }}"
         image: "{{ image }}"
         service_account_email: "{{ service_account_email }}"
         pem_file: "{{ pem_file }}"
         project_id: "{{ project_id }}"
         tags: webserver
     register: gce

   - name: Wait for SSH to come up
     wait_for: host={{ item.public_ip }} port=22 delay=10 timeout=60
     with_items: gce.instance_data

   - name: Install lighttpd
     apt: pkg=lighttpd state=installed
     sudo: True

   - name: Allow HTTP
     local_action: gce_net
     args:
         fwname: "all-http"
         name: "default"
         allowed: "tcp:80"
         state: "present"
         service_account_email: "{{ service_account_email }}"
         pem_file: "{{ pem_file }}"
         project_id: "{{ project_id }}"


#   - name: Add host to groupname
#     add_host: hostname={{ item.public_ip }} groupname=new_instances
#     with_items: gce.instance_data

#- name: Manage new instances
#  hosts: new_instances
#  connection: ssh
#  sudo: True

#  vars:
#    service_account_email: 2287590306-m6mip51l0ju92bf2kignpoeehbfca108@developer.gserviceaccount.com
#    pem_file: /Users/lane/google/pkey.pem
#    project_id: linear-arcadia-847
#    machine_type: n1-standard-1
#    image: debian-7

#  tasks:


#     - name: Install lighttpd
#       apt: pkg=lighttpd state=installed
#       sudo: True

#     - name: Allow HTTP
#       local_action: gce_net
#       args:
#         fwname: "all-http"
#         name: "default"
#         allowed: "tcp:80"
#         state: "present"
#         service_account_email: "{{ service_account_email }}"
#         pem_file: "{{ pem_file }}"
#         project_id: "{{ project_id }}"






